pipeline {
    agent any
    
    environment {
        GITHUB_REPO = 'https://github.com/yourusername/yourrepo.git'
        BRANCH = 'main'  // Change to 'master' or your branch
    }
    
    stages {
        stage('Clone Repository') {
            steps {
                git branch: env.BRANCH, credentialsId: 'github-token', url: env.GITHUB_REPO
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm run test'  // Modify based on your project
            }
        }

        stage('Build Project') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Deploy to cPanel') {
            steps {
                script {
                    def remote = ${secrets.SERVER}
                    def ftp_user = ${secrets.USERNAME}
                    def ftp_pass = ${secrets.PPASSWORD} // Use Jenkins credentials instead of plaintext

                    sh "lftp -c 'open -u ${secrets.USERNAME},${secrets.PPASSWORD} ${secrets.SERVER} && mirror -R dist . && bye'"
                }
            }
        }
    }
}
